import { cn } from '@/lib/utils';
import NavBar from '@/components/nav-bar';

import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light">
      <body className={cn(inter.className, 'bg-grid-slate-200/50')}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
