import {
  ArrowRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Cloud,
  Expand,
  File,
  Ghost,
  Loader2,
  MessageSquare,
  Plus,
  RotateCw,
  Search,
  Trash,
  XCircle,
} from 'lucide-react';

export const Icons = {
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  cloud: Cloud,
  expand: Expand,
  file: File,
  ghost: Ghost,
  loader2: Loader2,
  messageSquare: MessageSquare,
  plus: Plus,
  rotateCw: RotateCw,
  search: Search,
  trash: Trash,
  xCircle: XCircle,
};
